name: healskin
description: "Aplicación Móvil Inteligente para la Preservación del Cuidado de la Piel"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

  # HealSkin Core Tech Stack
  supabase_flutter: ^2.5.4 # Para la BD y Auth en tiempo real
  flutter_riverpod: ^2.5.1 # Para el manejo de estado
  google_fonts: ^6.2.1     # Para la tipografía

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
